config/routes.rb
Rails.application.routes.draw do
  get 'password_resets/new'
  get 'password_resets/edit'
  get 'sessions/new'

  root 'users#new'

  get '/terms',     to: 'static_pages#help'
  get '/signup',    to: 'users#new'
  post '/signup',   to: 'users#create'
  get '/change',    to: 'users#change'
  
  get '/login',     to: 'sessions#new'
  post '/login',    to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  
  resources :users do
    member do
      get :following, :followers, :change
      patch :renew
    end
  end
  
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :microposts,          only: [:new, :create, :destroy, :index]
  resources :relationships,       only: [:create, :destroy]
end

app/models/user.rb
class User < ApplicationRecord
  has_many :microposts, dependent: :destroy
  has_many :active_relationships, class_name:  "Relationship",
                                  foreign_key: "follower_id",
                                  dependent:   :destroy
  has_many :passive_relationships, class_name:  "Relationship",
                                   foreign_key: "followed_id",
                                   dependent:   :destroy
  has_many :following, through: :active_relationships, source: :followed
  has_many :followers, through: :passive_relationships, source: :follower
  
  attr_accessor :remember_token, :activation_token, :reset_token
  before_save   :downcase_email
  before_create :create_activation_digest
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :name,      presence: true, length: { maximum: 50 }
  validates :user_name, presence: true, length: { maximum: 50 }
  validates :email,     presence: true, length: { maximum: 255},
                        format: { with: VALID_EMAIL_REGEX },
                        uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }
  
  class << self
    
    def digest(string)
      cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                    BCrypt::Engine.cost
      BCrypt::Password.create(string, cost: cost)
    end
  
    def new_token
      SecureRandom.urlsafe_base64
    end
    
  end
  
  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end
  
  def authenticated?(attribute, token)
    digest = send("#{attribute}_digest")
    return false if digest.nil?
    BCrypt::Password.new(digest).is_password?(token)
  end
  
  def forget
    update_attribute(:remember_digest, nil)
  end
  
  def activate
    update_columns(activated: true, activated_at: Time.zone.now)
  end

  def send_activation_email
    UserMailer.account_activation(self).deliver_now
  end
  
  def create_reset_digest
    self.reset_token = User.new_token
    update_columns(reset_digest:  User.digest(reset_token),
                   reset_sent_at: Time.zone.now)
  end

  def send_password_reset_email
    UserMailer.password_reset(self).deliver_now
  end
  
  def password_reset_expired?
    reset_sent_at < 2.hours.ago
  end
  
  def feed
    Micropost.where("user_id IN (:following_ids) OR user_id = :user_id",
     following_ids: following_ids, user_id: id)
  end
  
  def follow(other_user)
    following << other_user
  end

  def unfollow(other_user)
    active_relationships.find_by(followed_id: other_user.id).destroy
  end

  def following?(other_user)
    following.include?(other_user)
  end
  
  
  private

    def downcase_email
      self.email.downcase!
    end

    def create_activation_digest
      self.activation_token  = User.new_token
      self.activation_digest = User.digest(activation_token)
    end
    
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:index, :edit, :update, :destroy,
                                        :following, :followers]
  before_action :correct_user,   only: [:edit, :update, :destroy]
  
  
  def new
    if logged_in?
      @user = current_user
      @micropost  = current_user.microposts.build
      @feed_items = current_user.feed.paginate(page: params[:page])
    else
      @user = User.new
    end
  end
  
  def create
    @user = User.new(user_params)
    if @user.save
      @user.send_activation_email
      flash[:info] = "Please check your email to activate your account."
      redirect_to root_url
    else
      render 'new'
    end
  end
  
  def show
    @user=User.find_by(id: params[:id])
    @microposts = @user.microposts.paginate(page: params[:page])
  end
  
  def edit
    @user = User.find(params[:id])
  end
  
  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      flash[:success] = "Profile updated"
      redirect_to @user
    else
      render 'edit'
    end
  end
  
  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User deleted"
    redirect_to users_url
  end
  
  #パスワード更新フォーム
  def change
    @user = current_user
  end
  
  #パスワード更新
  def renew
    @user = User.find_by(id: params[:id])
    if BCrypt::Password.new(@user.password_digest).is_password?(params[:user][:original_password])#@user.authenticate(params[:user][:original_password])
      if @user.update_attributes(user_params)
        flash[:success] = "Profile updated"
        redirect_to @user
      else
        render 'change'
      end
    else
      flash[:danger] = "パスワードが違います"
      render 'change'
    end
  end
  
  def following
    @title = "Following"
    @user  = User.find(params[:id])
    @users = @user.following.paginate(page: params[:page])
    render 'show_follow'
  end

  def followers
    @title = "Followers"
    @user  = User.find(params[:id])
    @users = @user.followers.paginate(page: params[:page])
    render 'show_follow'
  end

    
    private

      def user_params
        params.require(:user).permit(:name, :user_name, :email,
                                     :password, :password_confirmation)
      end
      
      # beforeアクション
      def correct_user
        @user = User.find(params[:id])
        redirect_to(root_url) unless current_user?(@user)
      end
      
      def admin_user
        redirect_to(root_url) unless current_user.admin?
      end
      
end

app/helpers/users_helper.rb
module UsersHelper
  
  def gravatar_for(user, options = { size: 80 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
  
  def logged_in?
    !current_user.nil?
  end
  
  def current_user
    if (user_id = session[:user_id])
      @current_user ||= User.find_by(id: user_id)
    elsif (user_id = cookies.signed[:user_id])
      user = User.find_by(id: user_id)
      if user && user.authenticated?(:remember, cookies[:remember_token])
        log_in user
        @current_user = user
      end
    end
  end
  
end

app/views/users/_follow.html.erb
<%= form_for(current_user.active_relationships.build, remote: true) do |f| %>
  <div><%= hidden_field_tag :followed_id, @user.id %></div>
  <%= f.submit "Follow", class: "btn btn-primary" %>
<% end %>

app/views/users/_follow_form.html.erb
<% unless current_user?(@user) %>
  <div id="follow_form">
  <% if current_user.following?(@user) %>
    <%= render 'unfollow' %>
  <% else %>
    <%= render 'follow' %>
  <% end %>
  </div>
<% end %>

app/views/users/_unfollow.html.erb
<%= form_for(current_user.active_relationships.find_by(followed_id: @user.id),
             html: { method: :delete }, remote: true) do |f| %>
  <%= f.submit "Unfollow", class: "btn" %>
<% end %>

app/views/users/_user.html.erb
<li>
  <%= gravatar_for user, size: 50 %>
  <%= link_to user.name, user %>
  <% if current_user.admin? && !current_user?(user) %>
    | <%= link_to "delete", user, method: :delete,
                                  data: { confirm: "You sure?" } %>
  <% end %>
</li>

app/views/users/change.html.erb
<% provide(:title, "パスワードを変更") %>
<h1>パスワードを変更</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user, url: {controller: 'users', action: 'renew' }) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>
      <%= f.label :original_password %>
      <%= f.password_field :original_password, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "Save changes", class: "btn btn-primary" %>
    <% end %>

    <div class="gravatar_edit">
      <%= gravatar_for @user %>
      <a href="http://gravatar.com/emails" target="_blank">change</a>
    </div>
  </div>
</div>

app/views/users/edit.html.erb
<% provide(:title, "プロフィールを編集") %>
<h1>プロフィールを編集</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>
      
      <%= f.label :user_name %>
      <%= f.text_field :user_name, class: 'form-control' %>


      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.submit "Save changes", class: "btn btn-primary" %>
    <% end %>

    <div class="gravatar_edit">
      <%= gravatar_for @user %>
      <a href="http://gravatar.com/emails" target="_blank">change</a>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<% provide(:title, 'explore') %>
<h1>All users</h1>

<%= will_paginate %>

<ul class="users">
  <%= render @users %>
</ul>

<%= will_paginate %>

app/views/users/new.html.erb
<% if logged_in? %>
<div class="row">
  <div class="col-md-7 col-md-offset-1">
    <h3>Micropost Feed</h3>
    <%= render 'shared/feed' %>
  </div>
  <div class="col-md-4">
    <section class="user_info">
      <h2>
        <%= gravatar_for @user %>
        <%= link_to @user.name, @user %>
      </h2>
      <h2>
        <%= @user.user_name %>
      </h2>
    </section>
  </div> 

<% else %>
<div class="row">
  <div class="col-md-4">
    <%= link_to image_tag("instagram_logo.png", alt: "Instagram logo"),'https://www.instagram.com' %>
  </div>
  <div class="col-md-6 col-md-offset-2 ">
    <% provide(:title, "Signup") %>
　　<h1>Instagram</h1>
　　<h2>友達の写真や動画をチェックしよう</h2>
　　<a href="#">
      <button type="button">Facebookでログイン</button>
　　</a>
　　<p>
　　  または
　　</p>
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>
      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>
      
      <%= f.label :user_name %>
      <%= f.text_field :user_name, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "Create my account", class: "btn btn-primary" %>
    <% end %>
    <p>
      アカウントをお持ちですか？ <%= link_to "ログインする", login_path %>
    </p>
  </div>
</div>
<% end %>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="container">
  <div class="row">
    <div class="col-md-4">
      <section class="user_info">
        <h2>
          <%= gravatar_for @user %>
          <%= @user.name %>
        </h2>
        <h2>
          <%= @user.user_name %>
        </h2>
      </section>
    </div>
    <div class="col-md-6 user_info">
      
    <div class="btn-group">
      <button class="btn btn-default btn-sm dropdown-toggle" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        プロフィールを編集<span class="caret"></span>
      </button>
      <ul class="dropdown-menu">
        <li>
          <%= link_to "プロフィール", @user %>
        </li>
        <li>
          <%= link_to "プロフィールを編集", edit_user_path(@user) %>
        </li>
        <li>
          <%= link_to "パスワードを変更", change_user_path(@user) %>
        </li>
        <li class="divider"></li>
        <li>
          <%= link_to "ログアウト", logout_path, method: :delete %>
        </li>
        <% if current_user == @user %>
          <li class="divider"></li>
          <li>
            <%= link_to "アカウントを削除", user_path(current_user), method: :delete %>
          </li>
        <% end %>
      </ul>
    </div>
    <%= render 'shared/stats' %>
    <%= render 'follow_form' if logged_in? %>
  </div>
  
  <div class="row">
    <% if @user.microposts.any? %>
      <% @microposts.each do |micropost| %>
        <div class="col-md-4 col-sm-4"> 
          <a href="#" class="thumbnail">
            <div class="image">
              <img src="<%= micropost.picture.url %>" class="img img-responsive  full-width" >
            </div>
          </a>
        </div>
      <% end %>
      <%= will_paginate @microposts %>
    <% end %>
  </div>
</div>
    
    
    
    
    

app/views/users/show_follow.html.erb
<% provide(:title, @title) %>
<div class="container">
<div class="row">
  <div class="col-md-4">
    <section class="user_info">
      <h2>
        <%= gravatar_for @user %>
        <%= @user.name %>
      </h2>
      <h2>
        <%= @user.user_name %>
      </h2>
    </section>
  </div>
  <div class="col-md-6 user_info">
    
  <div class="btn-group">
    <button class="btn btn-default btn-sm dropdown-toggle" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
      プロフィールを編集<span class="caret"></span>
    </button>
    <ul class="dropdown-menu">
      <li>
        <%= link_to "Profile", @user %>
      </li>
      <li>
        <%= link_to "Edit Profile", edit_user_path(@user) %>
      </li>
      <li>
        <%= link_to "Change Password", change_path %>
      </li>
      <li class="divider"></li>
      <li>
        <%= link_to "Log out", logout_path, method: :delete %>
      </li>
    </ul>
  </div>
  <%= render 'shared/stats' %>
  <%= render 'follow_form' if logged_in? %>
</div>

<div class="col-md-8">
  <h3><%= @title %></h3>
  <% if @users.any? %>
    <ul class="users follow">
      <%= render @users %>
    </ul>
    <%= will_paginate %>
  <% end %>
</div>