config/routes.rb
Rails.application.routes.draw do
  get 'password_resets/new'
  get 'password_resets/edit'
  get 'sessions/new'

  root 'users#new'

  get '/terms',     to: 'static_pages#help'
  get '/signup',    to: 'users#new'
  post '/signup',   to: 'users#create'
  get '/change',    to: 'users#change'
  
  get '/login',     to: 'sessions#new'
  post '/login',    to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  
  resources :users do
    member do
      get :following, :followers, :change
      patch :renew
    end
  end
  
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :microposts,          only: [:new, :create, :destroy, :index]
  resources :relationships,       only: [:create, :destroy]
end

app/views/layouts/_footer.html.erb
<% if logged_in? %>
<footer class="navbar navbar-fixed-bottom navbar-inverse">
  <div class="container">
    <nav>
      <ul class="nav navbar-nav navbar-left" >
        <li><%= link_to "home",  root_path %></li>
        <li><%= link_to "serch", '#'%></li>
        <li><%= link_to "Post",  new_micropost_path %></li>
      </ul>
      
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "like" ,   '#' %></li>
        <li><%= link_to "user",    '#' %></li>
      </ul>
    </nav>
  </div>
</footer>
<% end %>

<div class="row">
  <div class="col-md-12">
    <ul class="list-inline">
      <li class="list-inline-item"><%= link_to"INAGRAMについて", '#' %></li>
　　  <li class="list-inline-item"><%= link_to"サポートプレス", '#' %></li>
　　  <li class="list-inline-item"><%= link_to"API", '#' %></li>
　　  <li class="list-inline-item"><%= link_to"求人", '#' %></li>
　　  <li class="list-inline-item"><%= link_to"プライバシー", '#' %></li>
　　  <li class="list-inline-item"><%= link_to"利用規約", terms_path %></li>
　　  <li class="list-inline-item"><%= link_to"ディレクトリ", '#' %></li>
　　  <li class="list-inline-item"><%= link_to"プロフィール", '#' %></li>
　　  <li class="list-inline-item"><%= link_to"ハッシュタグ", '#' %></li>
　　  <li class="list-inline-item"><%= link_to"言語", '#' %></li>
　　</ul>
  </div>
</div>

app/views/layouts/_header.html.erb
<% if logged_in? %>
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "clone_app", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "search",  '#' %></li>
        <li><%= link_to "explore", microposts_path %></li>
        <li><%= link_to "like" ,   '#' %></li>
        <li><%= link_to "user",    current_user %></li>
      </ul>
    </nav>
  </div>
</header>
<% end %>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
      <%= csrf_meta_tags %>
      <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
      <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
      <%= render 'layouts/shim' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    
    <div class="container">
      <% flash.each do |message_type, message| %>
      <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>